### ISSUE TITLE
Opera Addon

### ISSUE THREAD

**Issue by shwetank** [brinchj/RndPhrase#14]
Opera is based on the same chrome extension model. Would be great to have this in the [opera addons catalog too](https://addons.opera.com).

**Comment by brinchj** [comment]
Hi!

I did not know that Opera supported Chrome extensions, that is very cool! :+1: 

I went ahead and uploaded the add-on, it is not waiting for approval.

I cannot say that I am spending much time improving this add-on, but then again it does kind of just work. 

Note that there is also a fork which may see more work these days:
https://github.com/RndPhrase


Thanks for the head's up though! :)

**Comment by shwetank** [comment]
Hey,

Thanks for that. It seems the screenshots were of a different browser, which is why it was not published right now. Would it be possible to give it another try with screenshots of it in the Opera browser? 

To help out, I've added a few screenshots here. If you think they're fine, maybe you could add those as screenshots? They are here http://imgur.com/a/cmwav 

Thanks so much :)

**Comment by brinchj** [comment]
Thanks for the screenshots! I've added them to the extension and that got us to almost approval.

Only a few comments remain, and I think fixing them would be compatible with Chrome, as it seems to be a matter of switching to newer Chrome APIs.

- options.html - please use label tag for input.
- Apply dedicated chrome.storage api instead of localStorage- options.js:121
- use textContent when working with plain text.
- modal.html and modal.js - redundant files. Please remove.
- options.html:1 - commented lines will be visible in rendered page.

Some of these are probably trivial, other a bit more messy. Feel free to give it a try if you have the time. I'm out next week, but I may take a look when I return next weekend.

**Comment by Munter** [comment]
The switch from loclalstorage to chrome.storage is a backwards incompatible change. There would have to be migration code in place to check localstorage and migrate existing seeds into chrome storage in order not to break existing installations

**Comment by brinchj** [comment]
The add-on was approved for Opera and is now live: 
https://addons.opera.com/en/extensions/details/rndphrase/?display=en

Thank you for your contributions!
